# Generated by Django 5.2.9 on 2026-01-13 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_core', '0018_therapy_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapyAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_patient', to=settings.AUTH_USER_MODEL)),
                ('therapy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_therapy', to='app_core.therapy')),
            ],
        ),
    ]
