# Generated by Django 5.2.9 on 2026-01-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_patient', '0003_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
