# Generated by Django 5.2.9 on 2026-02-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_patient', '0006_deliveryaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
