# Generated by Django 5.2.9 on 2026-02-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_patient', '0007_deliveryaddress_contact_deliveryaddress_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
