# Generated by Django 5.2.9 on 2026-02-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_patient', '0008_alter_deliveryaddress_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapyappointment',
            name='patient_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapyappointment',
            name='patient_gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='therapyappointment',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
