# Generated by Django 5.2.9 on 2026-02-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_patient', '0009_therapyappointment_patient_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapyappointment',
            name='guest_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapyappointment',
            name='guest_gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='therapyappointment',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
