# Generated by Django 5.2.9 on 2026-02-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_patient', '0010_therapyappointment_guest_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='guest_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='guest_gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='patient_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='patient_gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
