# Generated by Django 5.2.9 on 2026-02-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_patient', '0011_doctorappointment_guest_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapyappointment',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
