# Generated by Django 5.2.9 on 2026-02-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_patient', '0012_therapyappointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapyappointment',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
