# Generated by Django 5.2.9 on 2026-02-15 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_patient', '0013_doctorappointment_count_therapyappointment_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorappointment',
            old_name='count',
            new_name='capacity',
        ),
        migrations.RenameField(
            model_name='therapyappointment',
            old_name='count',
            new_name='capacity',
        ),
    ]
