# Generated by Django 5.2.9 on 2026-02-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_patient', '0014_rename_count_doctorappointment_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='capacity',
            field=models.PositiveIntegerField(default=5, help_text='Max appointments per day'),
        ),
        migrations.AlterField(
            model_name='therapyappointment',
            name='capacity',
            field=models.PositiveIntegerField(default=5, help_text='Max appointments per day'),
        ),
    ]
