# Generated by Django 5.2.9 on 2026-02-15 21:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_patient', '0015_alter_doctorappointment_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapyappointment',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='therapyappointment',
            name='guest_age',
        ),
        migrations.RemoveField(
            model_name='therapyappointment',
            name='guest_gender',
        ),
        migrations.RemoveField(
            model_name='therapyappointment',
            name='guest_name',
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='therapyappointment',
            name='patient_age',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
