# Generated by Django 5.2.9 on 2026-02-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_patient', '0016_remove_therapyappointment_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='patient_problems',
            field=models.TextField(blank=True, null=True),
        ),
    ]
