# Generated by Django 5.2.9 on 2026-02-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_patient', '0017_doctorappointment_patient_problems'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapyappointment',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
