# Generated by Django 5.2.9 on 2026-02-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_patient', '0018_therapyappointment_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
