# Generated by Django 5.2.9 on 2026-02-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_patient', '0019_doctorappointment_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
