# Generated by Django 5.2.9 on 2026-01-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregistration',
            name='age',
            field=models.CharField(),
        ),
    ]
