# Generated by Django 5.2.9 on 2026-02-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0004_alter_patientregi_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregi',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patientregi',
            name='age',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patientregi',
            name='contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patientregi',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patientregi',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patientregi',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
