# Generated by Django 5.2.9 on 2026-02-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard', '0005_alter_patientregi_address_alter_patientregi_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregi',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
