# Generated by Django 5.2.9 on 2026-01-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0005_remove_doctor_name_doctor_experience_doctor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='contact',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='schedule',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(),
        ),
    ]
