# Generated by Django 5.2.9 on 2026-01-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0006_alter_doctor_contact_alter_doctor_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapyname', models.CharField(max_length=100)),
                ('servicename', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('duration', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('benefits', models.TextField()),
                ('productused', models.CharField()),
            ],
        ),
    ]
