# Generated by Django 5.2.9 on 2026-01-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0007_therapy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='productused',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
