# Generated by Django 5.2.9 on 2026-01-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0008_alter_therapy_benefits_alter_therapy_productused'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapy',
            name='id',
        ),
        migrations.AddField(
            model_name='therapy',
            name='number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='benefits',
            field=models.TextField(null=True),
        ),
    ]
