# Generated by Django 5.2.9 on 2026-01-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0009_remove_therapy_id_therapy_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapy',
            name='number',
        ),
        migrations.AddField(
            model_name='therapy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
