# Generated by Django 5.2.9 on 2026-01-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0010_remove_therapy_number_therapy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(),
        ),
    ]
