# Generated by Django 5.2.9 on 2026-01-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0011_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
