# Generated by Django 5.2.9 on 2026-01-07 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0014_alter_therapy_therapyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapy',
            name='therapyname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_core.category'),
        ),
    ]
