# Generated by Django 5.2.9 on 2026-01-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0016_alter_therapy_therapyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapy',
            name='shortdescription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
