# Generated by Django 5.2.9 on 2026-01-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0017_therapy_shortdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapy',
            name='count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
