# Generated by Django 5.2.9 on 2026-01-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0018_therapy_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fee',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
