# Generated by Django 5.2.9 on 2026-01-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0019_doctor_fee_doctor_img_doctor_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='about',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(null=True),
        ),
    ]
