# Generated by Django 5.2.9 on 2026-01-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0020_doctor_about_doctor_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
