# Generated by Django 5.2.9 on 2026-01-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0023_doctor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
