# Generated by Django 5.2.9 on 2026-01-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0024_alter_doctor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
