# Generated by Django 5.2.9 on 2026-01-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0025_medicine_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine_category',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
