# Generated by Django 5.2.9 on 2026-01-27 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0026_medicine_category_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('price', models.CharField(max_length=50)),
                ('medicinecategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.medicine_category')),
            ],
        ),
    ]
