# Generated by Django 5.2.9 on 2026-01-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0028_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
