# Generated by Django 5.2.9 on 2026-01-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_first_name_user_last_name_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Docter', 'Docter'), ('Patient', 'Patient')], default='Admin'),
        ),
    ]
